# Generated by Django 5.0.2 on 2024-03-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ground',
            new_name='Homeground',
        ),
    ]
